//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimeco_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReport
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ProjectName { get; set; }
        public Nullable<decimal> LastMonthRemain { get; set; }
        public Nullable<decimal> SubTotalInput { get; set; }
        public Nullable<decimal> SubTotalOutput { get; set; }
        public Nullable<decimal> BankRemain { get; set; }
        public Nullable<decimal> CashInHand { get; set; }
        public Nullable<decimal> ProjectTotal { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
