//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimeco_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string WorkingTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> UnitPerHour { get; set; }
        public string Advanced { get; set; }
        public string Gasoline { get; set; }
        public string ProjectID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Note { get; set; }
    }
}
